# Generated by Django 5.2.11 on 2026-02-21 15:16

from django.db import migrations


def fill_new_building_data(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')

    for flat in Flat.objects.all():
        if flat.construction_year is None:
            continue
        flat.new_building = flat.construction_year >= 2015
        flat.save()


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0004_flat_new_building'),
    ]

    operations = [
        migrations.RunPython(fill_new_building_data),
    ]