# Generated by Django 5.2.11 on 2026-03-07 15:45

from django.db import migrations, models, transaction
import phonenumbers
from phonenumber_field.modelfields import PhoneNumberField

def normalize_phone_numbers(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')

    flat_objects = Flat.objects.all()
    for flat_object in flat_objects:
        raw_number = flat_object.owners_phonenumber
        parsed_number = None
        try:
            parsed_number = phonenumbers.parse(raw_number, 'RU')
        except phonenumbers.NumberParseException:
            flat_object.owner_pure_phone = None
        if parsed_number and phonenumbers.is_valid_number(parsed_number):
            pure_number = phonenumbers.format_number(parsed_number, phonenumbers.PhoneNumberFormat.E164)
            flat_object.owner_pure_phone = pure_number
            flat_object.save(update_fields=['owner_pure_phone'])
        else:
            flat_object.owner_pure_phone = None
            flat_object.save(update_fields=['owner_pure_phone'])

def move_backward(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    flat_objects = Flat.objects.all()
    for flat_object in flat_objects.iterator():
        flat_object.owner_pure_phone = None
        flat_object.save()

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_flat_owner_pure_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='owner_pure_phone',
            field=PhoneNumberField(
                verbose_name='Нормализованный номер владельца',
                blank=True,
                region='RU',
                null=True
            ),
        ),
        migrations.RunPython(normalize_phone_numbers),
    ]
