# Generated by Django 5.2.11 on 2026-03-21 15:51

from django.db import migrations, models

def migrate_owner_to_owners_model(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    Flat = apps.get_model('property', 'Flat')
    flat_objects = Flat.objects.all()
    for flat_object in flat_objects:
        Owner.objects.get_or_create(full_name=flat_object.owner,
                                    defaults={
                                        'phone_number': flat_object.owners_phonenumber,
                                        'pure_phone': flat_object.owner_pure_phone,
                                    })



class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_owner'),
    ]

    operations = [
        migrations.RunPython(migrate_owner_to_owners_model),
    ]

