# Generated by Django 5.2.12 on 2026-03-28 16:18

from django.db import migrations

def link_flats_to_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    owners = Owner.objects.all()

    for owner in owners.iterator():
        owner.flats.set(Flat.objects.filter(owner=owner.full_name))

def move_backward(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    Owner.objects.all().update(flats=[])


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_auto_20260321_1851'),
    ]

    operations = [
        migrations.RunPython(link_flats_to_owners, move_backward)
    ]
