# Generated by Django 5.2.13 on 2026-05-02 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_remove_flat_owner_remove_flat_owner_pure_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='new_building',
            field=models.BooleanField(db_index=True, default=None, null=True),
        ),
    ]
